name: Release Storybook

on:
  push:
    branches:
      - master

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build Storybook
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        run: pnpm build-storybook
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN_FOR_STORYBOOK }}
          publish_dir: ./storybook-static
